# sudo: required
language: objective-c
# language: node_js
node_js:
  - "0.10"

before_install:
  # Install phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip
  - unzip phantomjs-2.1.1-macosx.zip
  - export PATH="`pwd`/phantomjs-2.1.1-macosx/bin:${PATH}"
  # Run Arunoda's script
  - "curl -L https://git.io/ejPSng | /bin/sh"
script: "make test"

env:
  - METEOR_RELEASE=1.3.5.1

# Later stuff for Meteor 1.4: see https://github.com/arunoda/travis-ci-meteor-packages/pull/45
# env:
#   - CXX=g++-4.8 METEOR_RELEASE=1.3.5.1
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
